### ISSUE TITLE
"Alert - Error" modal after sending a Lightning Payment on iOS

### ISSUE THREAD

**Issue by mattnook** [BlueWallet/BlueWallet#279]
I am getting an error modal when trying to pay an invoice from mobile to the Woocommerce Lightning Gateway plugin (c-lightning implementation). Other wallet (Desktop Eclair) is working fine. BlueWallet is working fine on other sites like Yalls.org. Please advise, the modal provides little detail.

![img-0631](https://user-images.githubusercontent.com/16688198/51886713-937b4600-2356-11e9-8ef5-76ed6881de2b.JPG)
![img-0632](https://user-images.githubusercontent.com/16688198/51886718-970ecd00-2356-11e9-8c09-9640aa8f8ed1.JPG)

**Comment by Overtorment** [comment]
Hello! Looks like there's no direct channel with enough capacity to this
exact store.
If you can provide node address (or at least example of an invoice) I will
fix that.

**Comment by mattnook** [comment]
That would be great! here is the address:

02aecff209ee8e066e73df7b7881141007a72ab4055856b2f27b92a884bbf16aa8@170.75.175.231:9735

Thanks so much. BlueWallet has great UX by the way.

**Comment by Overtorment** [comment]
Done

**Comment by ArbenKarb** [comment]
I am getting the same error when trying to send from BlueWallet to my node. I figured the lack of a direct channel could've been the issue, so I've opened a direct channel to 03021c5f5f57322740e4ee6936452add19dc7ea7ccf90635f95119ab82a62ae268@207.180.244.165:9735 based on the LND uri at https://lndhub.herokuapp.com/.

However, still get the same error. 

I am able to pay lnd requests issued by my node with eclair mobile wallet.

**Comment by Overtorment** [comment]
You opened direct channel with capacity only in the direction of BW's node.
That means you have no incoming capacity. So BW's node cant pay you, that
is correct. You need to get incoming capacity for your node somehow
(thats the tricky part).

Also, you can use your own LND node with BlueWallet if you install
https://github.com/BlueWallet/LndHub/
and hook it with BW in settings.

**Comment by ArbenKarb** [comment]
Makes sense, thanks
