### ISSUE TITLE
App Crashes on send

### ISSUE THREAD

**Issue by Watchekong** [BlueWallet/BlueWallet#6272]
FIX: Application cashes on send in iso or android devices.

**Comment by marcosrdz** [comment]
Hello! What version and wallet type?

**Comment by pointbiz** [comment]
This happens in version 6.5.8 when you have a Bitcoin address in the clipboard it instantly crashes.

You must put something other than a Bitcoin address in the clipboard to get the app to load without crashing.

**Comment by marcosrdz** [comment]
> This happens in version 6.5.8 when you have a Bitcoin address in the clipboard it instantly crashes.
> 
> 
> 
> You must put something other than a Bitcoin address in the clipboard to get the app to load without crashing. 

This was fixed on 6.5.9

**Comment by Watchekong** [comment]
6.5.8Looking forward to your solution.  My BTC is in this wallet and I can’t get it out. Regards,It's another great day to be alive!On 15 Mar 2024, at 23:30, Marcos Rodriguez Vélez ***@***.***> wrote:﻿
Hello! What version and wallet type?

**Comment by marcosrdz** [comment]
> 6.5.8Looking forward to your solution.  My BTC is in this wallet and I can’t get it out. Regards,It's another great day to be alive!On 15 Mar 2024, at 23:30, Marcos Rodriguez Vélez ***@***.***> wrote:﻿
> 
> Hello! What version and wallet type?
> 
> 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Upgrade to 6.5.9

**Comment by Watchekong** [comment]
The wallet only gives an Error on send on an iPhone 13.  So I still can’t send funds.Looking forward to your reply.Regards,It's another great day to be alive!On 16 Mar 2024, at 03:59, Marcos Rodriguez Vélez ***@***.***> wrote:﻿

This happens in version 6.5.8 when you have a Bitcoin address in the clipboard it instantly crashes.
You must put something other than a Bitcoin address in the clipboard to get the app to load without crashing.

This was fixed on 6.5.9

**Comment by marcosrdz** [comment]
The replies are a bit confusing. Is the issue resolved?
