### ISSUE TITLE
Already installed BW app on iPad after last update will not open

### ISSUE THREAD

**Issue by sevadevi** [BlueWallet/BlueWallet#768]
Reporting the bug. Already installed BW app on iPad with iOS 9.3.5 after last update will not open. Please help.

**Comment by marcosrdz** [comment]
Are you getting any error? 

If possible, do a screen recording of the problem.

**Comment by sevadevi** [comment]
No error. When I tap to open the app, for a second all screen goes white, but immediately closes and you end up back on the Home screen full of apps.

**Comment by sevadevi** [comment]
{"bug_type":"109","os_version":"iPhone OS 9.3.5

**Comment by marcosrdz** [comment]
Ok. I'll look into this.

**Comment by sevadevi** [comment]
Thanks. I will send you diagnostic data on email right now.

**Comment by marcosrdz** [comment]
https://discussions.apple.com/thread/7632006

Other apps seem to have the same diagnostic error. If you have your wallet seed backups, please uninstall and reinstall the app.

**Comment by Overtorment** [comment]
Also, you can do this: open app, and once it crashes, relaunch it several times. Then go to https://ifconfig.co  and send your IP address to bluewallet@bluewallet.io
This way we will be able to find crash reports on our crash analytics system and see what went wrong.
This issue is now closed.

**Comment by sevadevi** [comment]
Thanks. Will do now.

**Comment by bearsylla** [comment]
Any update on this issue? I have not launch my bluewallet for months and just noticed that i can't open it after the update. I can't find my backup so reinstalling and restore wont work for me.

**Comment by ncoelho** [comment]
This issue was fixed some months ago. You may be running into a different one, mind sharing your phone/os so we can try to debug it? @bearsylla

**Comment by sevadevi** [comment]
same here. still waiting for an update.

**Comment by sevadevi** [comment]
Not yet. I have same issue @bearsylla. Please help

**Comment by bearsylla** [comment]
> This issue was fixed some months ago. You may be running into a different one, mind sharing your phone/os so we can try to debug it? @bearsylla

It is iPad2 9.3.5. and actually i had that issue back in December but i didn't have time to look into it and hope that it will resolve in next release. Then i just updated the app again last week, and it still doesn't work. I have follow the instruction above to launch the app several time and email bluewallet my IP address.
